version: 1
services:
  - type: web
    name: your-service-name
    env: node
    buildCommand: |
      apt-get update && apt-get install -y openjdk-17-jdk && npm install
    startCommand: npm start
    envVars:
      NODE_ENV: production
    plan: standard
